HAI Fix for githooks

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -1,13 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 
 hooks="$(dirname "$0")/pre-push.d"
 
 for hook in ${hooks}/*; do
-    bash $hook
+    echo "Running $hook."
+    bash "${hook}"
     RESULT=$?
-    if [ $RESULT != 0 ]; then
-        echo "pre-push.d/$hook returned non-zero: $RESULT, abort push"
-        exit $RESULT
+    if [[ ${RESULT} != 0 ]]; then
+        echo "${hook} returned non-zero: ${RESULT}, abort push"
+        exit ${RESULT}
     fi
 done
 
